#!/bin/sh
setenforce 0 >/dev/null 2>&1
killall openvpn >/dev/null 2>&1
killall -HUP mproxy >/dev/null 2>&1
killall squid >/dev/null 2>&1
squid -z >/dev/null 2>&1
squid -s >/dev/null 2>&1
killall squid >/dev/null 2>&1
squid -z >/dev/null 2>&1
squid -s >/dev/null 2>&1
systemctl start openvpn@server >/dev/null 2>&1
systemctl start openvpn@server-udp53 >/dev/null 2>&1
systemctl start httpd >/dev/null 2>&1
/var/www/html/res/jiankong >>/home/jiankong.log 2>&1 &
clear
/bin/mproxy -l 8080 -d >/dev/null 2>&1
echo
sleep 1
echo -e "服务状态：                    [\033[32m  OK  \033[0m]"
exit 0;